# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Decrypt_settings_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Decrypt_settings_window(object):
    def setupUi(self, Decrypt_settings_window):
        Decrypt_settings_window.setObjectName("Decrypt_settings_window")
        Decrypt_settings_window.resize(900, 734)
        self.textBrowser = QtWidgets.QTextBrowser(Decrypt_settings_window)
        self.textBrowser.setGeometry(QtCore.QRect(50, 180, 801, 431))
        self.textBrowser.setObjectName("textBrowser")
        self.pushDecryptButton = QtWidgets.QPushButton(Decrypt_settings_window)
        self.pushDecryptButton.setGeometry(QtCore.QRect(370, 660, 141, 41))
        self.pushDecryptButton.setObjectName("pushDecryptButton")
        self.label = QtWidgets.QLabel(Decrypt_settings_window)
        self.label.setGeometry(QtCore.QRect(50, 30, 51, 31))
        self.label.setObjectName("label")
        self.plainKeyEdit = QtWidgets.QPlainTextEdit(Decrypt_settings_window)
        self.plainKeyEdit.setGeometry(QtCore.QRect(50, 70, 461, 81))
        self.plainKeyEdit.setObjectName("plainKeyEdit")

        self.retranslateUi(Decrypt_settings_window)
        QtCore.QMetaObject.connectSlotsByName(Decrypt_settings_window)

    def retranslateUi(self, Decrypt_settings_window):
        _translate = QtCore.QCoreApplication.translate
        Decrypt_settings_window.setWindowTitle(_translate("Decrypt_settings_window", "Dialog"))
        self.pushDecryptButton.setText(_translate("Decrypt_settings_window", "Decrypt"))
        self.label.setText(_translate("Decrypt_settings_window", "Key:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Decrypt_settings_window = QtWidgets.QDialog()
    ui = Ui_Decrypt_settings_window()
    ui.setupUi(Decrypt_settings_window)
    Decrypt_settings_window.show()
    sys.exit(app.exec_())
